"""
Export Utilities
Generate and export results as files (CSV, joblib, markdown reports)
"""

import pandas as pd
import joblib
from pathlib import Path
from datetime import datetime


def export_leaderboard_csv(leaderboard, output_path="leaderboard.csv"):
    """
    Export model leaderboard as CSV
    
    Args:
        leaderboard: List of dicts with {'model': name, 'score': value}
        output_path: Path to save CSV file
    
    Returns: Path to saved file
    """
    df = pd.DataFrame(leaderboard)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(output_path, index=False)
    return str(output_path)


def export_best_model(model, output_path="best_model.joblib"):
    """
    Export trained model as joblib file
    
    Args:
        model: Trained sklearn model
        output_path: Path to save model file
    
    Returns: Path to saved file
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(model, output_path)
    return str(output_path)


def generate_experiment_report(
    best_model_name,
    task_type,
    dataset_summary,
    leaderboard,
    best_metrics,
    overfitting_analysis=None,
    cv_metrics=None,
    feature_importance_df=None,
    output_path="report.md"
):
    """
    Generate comprehensive markdown report of experiment
    
    Args:
        best_model_name: Name of best performing model
        task_type: 'classification' or 'regression'
        dataset_summary: Dict with rows, columns, features
        leaderboard: List of model results
        best_metrics: Dict of metrics for best model
        overfitting_analysis: Optional dict with overfitting stats
        cv_metrics: Optional dict with CV statistics
        feature_importance_df: Optional DataFrame of feature importance
        output_path: Path to save report
    
    Returns: Path to saved file
    """
    
    report = f"""# AutoML Experiment Report
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## 🎯 Experiment Summary
- **Task Type**: {task_type.title()}
- **Best Model**: {best_model_name}
- **Dataset Rows**: {dataset_summary.get('rows', 'N/A')}
- **Features**: {dataset_summary.get('features', 'N/A')}

## 📊 Best Model Performance
"""
    
    for metric_name, metric_value in best_metrics.items():
        if isinstance(metric_value, float):
            report += f"- **{metric_name.title()}**: {metric_value:.4f}\n"
        else:
            report += f"- **{metric_name.title()}**: {metric_value}\n"
    
    report += f"\n## 🏆 Model Leaderboard\n"
    for i, result in enumerate(leaderboard, 1):
        score = result.get('score', 'N/A')
        if isinstance(score, float):
            report += f"{i}. **{result['model']}**: {score:.4f}\n"
        else:
            report += f"{i}. **{result['model']}**: {score}\n"
    
    if overfitting_analysis:
        report += f"""
## 🔬 Model Health Analysis
- **Risk Level**: {overfitting_analysis.get('risk_level', 'N/A').title()}
- **Train Score**: {overfitting_analysis.get('train_score', 'N/A')}
- **Test Score**: {overfitting_analysis.get('test_score', 'N/A')}
- **Gap**: {overfitting_analysis.get('gap', 'N/A')}
- **Assessment**: {overfitting_analysis.get('verdict', 'N/A')}
"""
    
    if cv_metrics:
        report += f"""
## 📈 Cross-Validation Results
- **CV Mean**: {cv_metrics.get('cv_mean', 'N/A')}
- **CV Std**: {cv_metrics.get('cv_std', 'N/A')}
- **Fold Scores**: {', '.join(str(s) for s in cv_metrics.get('cv_scores', []))}
"""
    
    if feature_importance_df is not None and not feature_importance_df.empty:
        report += f"\n## ⭐ Top Features\n"
        top_features = feature_importance_df.head(10)
        for _, row in top_features.iterrows():
            report += f"- {row['Feature']}: {row['Importance']:.4f}\n"
    
    report += f"""
## 📋 Experiment Configuration
- Model Selection: Automatic GridSearchCV
- Train-Test Split: 80-20
- Preprocessing: StandardScaler for numeric, OneHotEncoder for categorical
- Cross-Validation: 5-fold CV

---
*Report generated by DataPilot AutoML*
"""
    
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(report, encoding='utf-8')
    
    return str(output_path)


def export_results_summary(results_dict, output_path="results_summary.json"):
    """
    Export complete results as JSON
    
    Args:
        results_dict: Dictionary with all results
        output_path: Path to save JSON file
    
    Returns: Path to saved file
    """
    import json
    
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Convert numpy types to native Python types for JSON serialization
    def convert_types(obj):
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        elif isinstance(obj, (np.integer, np.floating)):
            return float(obj)
        elif isinstance(obj, dict):
            return {k: convert_types(v) for k, v in obj.items()}
        elif isinstance(obj, (list, tuple)):
            return [convert_types(item) for item in obj]
        return obj
    
    with open(output_path, 'w') as f:
        json.dump(convert_types(results_dict), f, indent=2)
    
    return str(output_path)
